# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/riccardo/Documenti/VivadoVitisProjects/Particle-Detector-ARTY-A7/Darticle-Detector-ARTY-A7/Darticle-Detector-ARTY-A7.runs/synth_1/muon_telescope_top_module.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param xicom.use_bs_reader 1
set_param chipscope.maxJobs 2
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a35ticsg324-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/riccardo/Documenti/VivadoVitisProjects/Particle-Detector-ARTY-A7/Darticle-Detector-ARTY-A7/Darticle-Detector-ARTY-A7.cache/wt [current_project]
set_property parent.project_path /home/riccardo/Documenti/VivadoVitisProjects/Particle-Detector-ARTY-A7/Darticle-Detector-ARTY-A7/Darticle-Detector-ARTY-A7.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:arty-a7-35:part0:1.1 [current_project]
set_property ip_output_repo /home/riccardo/Documenti/VivadoVitisProjects/Particle-Detector-ARTY-A7/Darticle-Detector-ARTY-A7/Darticle-Detector-ARTY-A7.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib -sv {
  /home/riccardo/Documenti/VivadoVitisProjects/Particle-Detector-ARTY-A7/Firmware-SRC/Buffers_reg.sv
  /home/riccardo/Documenti/VivadoVitisProjects/Particle-Detector-ARTY-A7/Firmware-SRC/DAQ.sv
  /home/riccardo/Documenti/VivadoVitisProjects/Particle-Detector-ARTY-A7/Firmware-SRC/DC_blocker.sv
  /home/riccardo/Documenti/VivadoVitisProjects/Particle-Detector-ARTY-A7/Firmware-SRC/DSP_pipeline.sv
  /home/riccardo/Documenti/VivadoVitisProjects/Particle-Detector-ARTY-A7/Firmware-SRC/Frequency_Divider.sv
  /home/riccardo/Documenti/VivadoVitisProjects/Particle-Detector-ARTY-A7/Firmware-SRC/Monostable.sv
  /home/riccardo/Documenti/VivadoVitisProjects/Particle-Detector-ARTY-A7/Firmware-SRC/Monostable_rise_only.sv
  /home/riccardo/Documenti/VivadoVitisProjects/Particle-Detector-ARTY-A7/Firmware-SRC/Peak_detector.sv
  /home/riccardo/Documenti/VivadoVitisProjects/Particle-Detector-ARTY-A7/Firmware-SRC/Printer_uart.sv
  /home/riccardo/Documenti/VivadoVitisProjects/Particle-Detector-ARTY-A7/Firmware-SRC/SynchroCounter_4_bit.sv
  /home/riccardo/Documenti/VivadoVitisProjects/Particle-Detector-ARTY-A7/Firmware-SRC/Trigger.sv
  /home/riccardo/Documenti/VivadoVitisProjects/Particle-Detector-ARTY-A7/Firmware-SRC/XADC_module.sv
  /home/riccardo/Documenti/VivadoVitisProjects/Particle-Detector-ARTY-A7/Firmware-SRC/adc_demux.sv
  /home/riccardo/Documenti/VivadoVitisProjects/Particle-Detector-ARTY-A7/Firmware-SRC/baud_gen.sv
  /home/riccardo/Documenti/VivadoVitisProjects/Particle-Detector-ARTY-A7/Firmware-SRC/binary_BCD.sv
  /home/riccardo/Documenti/VivadoVitisProjects/Particle-Detector-ARTY-A7/Firmware-SRC/db_fsm.sv
  /home/riccardo/Documenti/VivadoVitisProjects/Particle-Detector-ARTY-A7/Firmware-SRC/debouncing_array.sv
  /home/riccardo/Documenti/VivadoVitisProjects/Particle-Detector-ARTY-A7/Firmware-SRC/left_padding.sv
  /home/riccardo/Documenti/VivadoVitisProjects/Particle-Detector-ARTY-A7/Firmware-SRC/test_unit.sv
  /home/riccardo/Documenti/VivadoVitisProjects/Particle-Detector-ARTY-A7/Firmware-SRC/threshold_controller.sv
  /home/riccardo/Documenti/VivadoVitisProjects/Particle-Detector-ARTY-A7/Firmware-SRC/time_measurement.sv
  /home/riccardo/Documenti/VivadoVitisProjects/Particle-Detector-ARTY-A7/Firmware-SRC/uart.sv
  /home/riccardo/Documenti/VivadoVitisProjects/Particle-Detector-ARTY-A7/Firmware-SRC/uart_rx.sv
  /home/riccardo/Documenti/VivadoVitisProjects/Particle-Detector-ARTY-A7/Firmware-SRC/uart_tx.sv
  /home/riccardo/Documenti/VivadoVitisProjects/Particle-Detector-ARTY-A7/Firmware-SRC/muon_telescope_top.sv
}
read_verilog -library xil_defaultlib /home/riccardo/Documenti/VivadoVitisProjects/Particle-Detector-ARTY-A7/Firmware-SRC/xadc__netlist.v
read_vhdl -library xil_defaultlib {
  /home/riccardo/Documenti/VivadoVitisProjects/Particle-Detector-ARTY-A7/Firmware-SRC/SPI_master_dual_miso.vhd
  /home/riccardo/Documenti/VivadoVitisProjects/Particle-Detector-ARTY-A7/Firmware-SRC/pmod_wrapper.vhd
}
read_ip -quiet /home/riccardo/Documenti/VivadoVitisProjects/Particle-Detector-ARTY-A7/Firmware-SRC/fifo_generator_time/fifo_generator_time.xci
set_property used_in_implementation false [get_files -all /home/riccardo/Documenti/FPGAtmos_pARTYcle_detector.gen/sources_1/ip/fifo_generator_time/fifo_generator_time.xdc]
set_property used_in_implementation false [get_files -all /home/riccardo/Documenti/FPGAtmos_pARTYcle_detector.gen/sources_1/ip/fifo_generator_time/fifo_generator_time_ooc.xdc]

read_ip -quiet /home/riccardo/Documenti/VivadoVitisProjects/Particle-Detector-ARTY-A7/Firmware-SRC/fifo_generator_area/fifo_generator_area.xci
set_property used_in_implementation false [get_files -all /home/riccardo/Documenti/FPGAtmos_pARTYcle_detector.gen/sources_1/ip/fifo_generator_area/fifo_generator_area.xdc]
set_property used_in_implementation false [get_files -all /home/riccardo/Documenti/FPGAtmos_pARTYcle_detector.gen/sources_1/ip/fifo_generator_area/fifo_generator_area_ooc.xdc]

read_ip -quiet /home/riccardo/Documenti/VivadoVitisProjects/Particle-Detector-ARTY-A7/Firmware-SRC/fifo_generator_uart/fifo_generator_uart.xci
set_property used_in_implementation false [get_files -all /home/riccardo/Documenti/FPGAtmos_pARTYcle_detector.gen/sources_1/ip/fifo_generator_uart/fifo_generator_uart.xdc]
set_property used_in_implementation false [get_files -all /home/riccardo/Documenti/FPGAtmos_pARTYcle_detector.gen/sources_1/ip/fifo_generator_uart/fifo_generator_uart_ooc.xdc]

read_ip -quiet /home/riccardo/Documenti/VivadoVitisProjects/Particle-Detector-ARTY-A7/Firmware-SRC/fifo_generator_peak/fifo_generator_peak.xci
set_property used_in_implementation false [get_files -all /home/riccardo/Documenti/FPGAtmos_pARTYcle_detector.gen/sources_1/ip/fifo_generator_peak/fifo_generator_peak.xdc]
set_property used_in_implementation false [get_files -all /home/riccardo/Documenti/FPGAtmos_pARTYcle_detector.gen/sources_1/ip/fifo_generator_peak/fifo_generator_peak_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/riccardo/Documenti/VivadoVitisProjects/Particle-Detector-ARTY-A7/Firmware-XDC/Arty-A7-35-Master.xdc
set_property used_in_implementation false [get_files /home/riccardo/Documenti/VivadoVitisProjects/Particle-Detector-ARTY-A7/Firmware-XDC/Arty-A7-35-Master.xdc]

set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental /home/riccardo/Documenti/VivadoVitisProjects/Particle-Detector-ARTY-A7/Darticle-Detector-ARTY-A7/Darticle-Detector-ARTY-A7.srcs/utils_1/imports/synth_1/muon_telescope_top_module.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top muon_telescope_top_module -part xc7a35ticsg324-1L
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef muon_telescope_top_module.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file muon_telescope_top_module_utilization_synth.rpt -pb muon_telescope_top_module_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
