# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/riccardo/Documenti/VivadoVitisProjects/Particle-Detector-ARTY-A7/Firmware-SRC/fifo_generator_area/fifo_generator_area.xci
# IP: The module: 'fifo_generator_area' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/riccardo/Documenti/FPGAtmos_pARTYcle_detector.gen/sources_1/ip/fifo_generator_area/fifo_generator_area.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_area'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/riccardo/Documenti/FPGAtmos_pARTYcle_detector.gen/sources_1/ip/fifo_generator_area/fifo_generator_area_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_area'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/riccardo/Documenti/VivadoVitisProjects/Particle-Detector-ARTY-A7/Firmware-SRC/fifo_generator_area/fifo_generator_area.xci
# IP: The module: 'fifo_generator_area' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/riccardo/Documenti/FPGAtmos_pARTYcle_detector.gen/sources_1/ip/fifo_generator_area/fifo_generator_area.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_area'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/riccardo/Documenti/FPGAtmos_pARTYcle_detector.gen/sources_1/ip/fifo_generator_area/fifo_generator_area_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_area'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
